name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        chmod +x setup.sh
        ./setup.sh

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Adjust PYTHONPATH to include the tests directory
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/tests" >> $GITHUB_ENV

    - name: Run tests
      run: pytest
